type Collection {
  contractPackageHash: String!
  contractHash: String!
  slug: String!
  name: String!
  symbol: String!
  description: String
  verified: Boolean!
  promoted: Boolean!
  image: String
  logo: String
  twitter: String
  discord: String
}

type PaginationInfo {
  total: Int!
  limit: Int!
  currentPage: Int!
  totalPages: Int!
  pageCounter: Int!
  hasPrev: Boolean!
  hasNext: Boolean!
  prevPage: Boolean!
  nextPage: Int!
}

type GetCollectionsResponse {
  collections: [Collection!]
  paginationInfo: PaginationInfo!
}

type Slug {
  slug: String!
  contractHash: String!
}

type GetCollectionSlugsResponse {
  data: [Slug!]
}

type Query {
  getCollections(
    query: String!
    page: Int!
    limit: Int!
  ): GetCollectionsResponse
  getCollectionSlugs: GetCollectionSlugsResponse
}

type Mutation {
  addCollection(
    contractPackageHash: String!
    contractHash: String!
    slug: String
    symbol: String!
    name: String!
    description: String
    verified: Boolean!
    promoted: Boolean
    image: String
    twitter: String
    discord: String
  ): Collection
}
