scalar Metadata
scalar GraphQLDate
scalar GraphQLLong

type Sale {
  creator: String!
  price: String!
  payToken: String
  startTime: GraphQLLong!
  status: String!
  createdAt: GraphQLDate!
  updatedAt: GraphQLDate!
}

type Token {
  collection: Collection!
  tokenId: String!
  metadata: Metadata!
  favoritedUsers: [String!]
  viewed: Int!
  owner: String!
  sales: [Sale!]
  pendingSale: Sale
}

type GetTokensResponse {
  tokens: [Token!]
  paginationInfo: PaginationInfo!
}

input GetTokensInput {
  slug: String
  owner: String
  tokenId: String
  promoted: Boolean
}

type Query {
  getTokens(where: GetTokensInput!, page: Int, limit: Int): GetTokensResponse
}

type TokenResponse {
  token: Token!
}

type Mutation {
  addToken(contractHash: String!, tokenId: String!): TokenResponse
  favoriteToken(
    slug: String!
    tokenId: String!
    publicKey: String!
  ): TokenResponse
}
