version: '3.7'

services:
  #cache redis
  redis:
    container_name: kunft-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  #backend
  kunft:
    build:
      context: .
    container_name: kunft
    env_file:
      - ./.env
    restart: always
    command: pnpm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    depends_on:
      - kunft-redis
    ports:
      - 8000:8000
