import Head from 'next/head'

import type { NextPage } from 'next'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Swappery & KUNFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/fonts/server.css" />
      </Head>

      <main className={styles.main} />
    </div>
  )
}

export default Home
