/* eslint-disable prefer-destructuring */
const NEXT_PUBLIC_CASPER_NODE_ADDRESS =
  process.env.NEXT_PUBLIC_CASPER_NODE_ADDRESS
const NEXT_PUBLIC_CASPER_EVENT_STREAM_ADDRESS =
  process.env.NEXT_PUBLIC_CASPER_EVENT_STREAM_ADDRESS
const NEXT_PUBLIC_MARKET_PLACE_CONTRACT_PACKAGE_HASH =
  process.env.NEXT_PUBLIC_MARKET_PLACE_CONTRACT_PACKAGE_HASH
const NEXT_PUBLIC_CASPER_CHAIN_NAME = process.env.NEXT_PUBLIC_CASPER_CHAIN_NAME

export {
  NEXT_PUBLIC_CASPER_NODE_ADDRESS,
  NEXT_PUBLIC_CASPER_CHAIN_NAME,
  NEXT_PUBLIC_CASPER_EVENT_STREAM_ADDRESS,
  NEXT_PUBLIC_MARKET_PLACE_CONTRACT_PACKAGE_HASH,
}
