fragment CollectionFields on Collection {
  contractPackageHash
  contractHash
  name
  description
  symbol
  slug
  background
  logo
  verified
  promoted
}

fragment PaginationFields on PaginationInfo {
  total
  limit
  currentPage
  totalPages
  hasPrev
  hasNext
}

query getCollections($query: String, $page: Int, $limit: Int) {
  getCollections(query: $query, page: $page, limit: $limit) {
    collections {
      ...CollectionFields
    }
    paginationInfo {
      ...PaginationFields
    }
  }
}

query getMetadataInfo($slug: String!) {
  getMetadataInfo(slug: $slug) {
    data {
      trait
      total
      distinctValues {
        value
        count
        percent
      }
    }
  }
}
