fragment SaleFields on Sale {
  creator
  price
  payToken
  startTime
  status
  createdAt
}

fragment TokenFields on Token {
  collection {
    ...CollectionFields
  }
  tokenId
  metadata
  favoritedUsers
  viewed
  owner
  pendingSale {
    ...SaleFields
  }
  sales {
    ...SaleFields
  }
}

query getTokens($where: GetTokensInput!, $page: Int, $limit: Int) {
  getTokens(where: $where, page: $page, limit: $limit) {
    tokens {
      ...TokenFields
    }
    paginationInfo {
      ...PaginationFields
    }
  }
}

mutation addOrUpdateToken($contractHash: String!, $tokenId: String!) {
  addToken(contractHash: $contractHash, tokenId: $tokenId) {
    token {
      ...TokenFields
    }
  }
}

mutation favoriteToken($slug: String!, $tokenId: String!, $publicKey: String!) {
  favoriteToken(slug: $slug, tokenId: $tokenId, publicKey: $publicKey) {
    token {
      ...TokenFields
    }
  }
}
